# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1acd4d348fb73d9aae1bcc84b597c22ea412580a79092b88a613296ea2fe018d13e9c6d6529ed268f5fa90b568095d34c67f5f684ebba63097d7bac1a6cd3a08

test:
  secret_key_base: 10ceb52c595dfd78ea34005b6e9f7816e3c9fc1f94b9ff3ef12719e4fe07077fd26746c1c9a3f80c6b513e908122b6dcbfd31311e47c22e69215b58eec4dc4e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
